import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../../db';
import { format } from 'date-fns';
import { FileText, User } from 'lucide-react';

export const ReportHistory = () => {
    // Show last 20 reports
    const logs = useLiveQuery(() =>
        db.report_logs.orderBy('generated_at').reverse().limit(20).toArray()
    );

    if (!logs?.length) {
        return (
            <div className="text-center py-12 bg-gray-50 rounded-2xl border border-dashed border-gray-200">
                <FileText className="mx-auto text-gray-300 mb-2" size={32} />
                <p className="text-gray-400 font-medium">No report history yet.</p>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            <h3 className="font-bold text-gray-900 px-1">Recent History</h3>
            <div className="grid gap-3">
                {logs.map(log => (
                    <div key={log.id} className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-gray-50 rounded-lg text-gray-500">
                                <FileText size={18} />
                            </div>
                            <div>
                                <p className="font-bold text-gray-800 text-sm">{log.type.replace('_', ' ')}</p>
                                <p className="text-xs text-gray-500">
                                    {format(new Date(log.generated_at), 'MMM dd, HH:mm')}
                                </p>
                            </div>
                        </div>

                        <div className="flex items-center gap-4 text-right">
                            <div className="hidden sm:block">
                                <p className="text-[10px] text-gray-400 uppercase font-bold">Generated By</p>
                                <div className="flex items-center justify-end gap-1 text-xs font-medium text-gray-600">
                                    <User size={12} /> {log.generated_by || 'System'}
                                </div>
                            </div>

                            {/* Summary Snippet */}
                            {log.result_summary && (
                                <div className="text-right">
                                    <p className="text-[10px] text-gray-400 uppercase font-bold">
                                        {(log.type === 'DISCOUNT_SUMMARY' || log.type === 'DISCOUNT_BOOK') ? 'Total Discount' :
                                            (log.type === 'SALES_BOOK') ? 'Total Gross' :
                                                (log.type.includes('READING')) ? 'Total Sales' :
                                                    'Gross Sales'}
                                    </p>
                                    <p className="font-mono font-bold text-gray-900 text-sm">
                                        {(
                                            // Discount Reports
                                            log.result_summary.total_discount_given ||
                                            log.result_summary.total_discount ||
                                            // Sales Reports
                                            log.result_summary.total_gross ||
                                            log.result_summary.gross_sales ||
                                            // Readings
                                            log.result_summary.total_sales ||
                                            0
                                        ).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                    </p>
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};
